(() => {
  const DEFAULTS={enabled:true,hideChat:false,hideTwitch:false,focusMode:false,lowTimeWarning:true,warningSeconds:30,criticalSeconds:10,showOpponentScore:true,showSessionPanel:true};
  const state={settings:{...DEFAULTS},session:null,lastGame:null,lastResultKey:null,opponent:null};
  const q=(s)=>Array.from(document.querySelectorAll(s));
  const qAny=(arr)=>arr.flatMap(q);
  const text=(e)=>((e?.textContent||'').replace(/\s+/g,' ').trim());
  const visible=e=>{if(!e)return false;const r=e.getBoundingClientRect(),c=getComputedStyle(e);return r.width>0&&r.height>0&&c.display!=='none'&&c.visibility!=='hidden'};
  const selectors={board:['wc-chess-board','chess-board'],clock:['.clock-component','.clock-time-monospace','[role="timer"]'],chat:['.chat-scroll-area-component','[class*="chat"]'],twitch:['iframe[src*="twitch.tv"]','iframe[src*="player.twitch.tv"]','[class*="stream"]'],players:['.player-component .player-name','.player-name','a[href*="/member/"]'],result:['[data-cy="game-over-modal-content"]','.game-over-modal-shell-content','.modal-game-over-component','.game-result-header']};
  const get=keys=>new Promise(r=>chrome.storage.local.get(keys,r));
  const set=v=>new Promise(r=>chrome.storage.local.set(v,r));
  function root(){let r=document.getElementById('zen-root');if(!r){r=document.createElement('div');r.id='zen-root';document.documentElement.appendChild(r)}return r}
  function hide(list,on){qAny(list).forEach(e=>e.classList.toggle('zen-hidden-by-extension',on))}
  function parseClock(v){const s=text(v).replace(/[^0-9:]/g,'');if(!s)return null;const p=s.split(':').map(Number);return p.length===2?p[0]*60+p[1]:p[0]}
  function clockWarn(){if(!state.settings.lowTimeWarning)return;qAny(selectors.clock).forEach(e=>{const s=parseClock(e);e.classList.remove('zen-clock-warning','zen-clock-critical');if(s==null)return;if(s<=state.settings.criticalSeconds)e.classList.add('zen-clock-critical');else if(s<=state.settings.warningSeconds)e.classList.add('zen-clock-warning')})}
  function apply(){document.documentElement.classList.toggle('zen-enabled',!!state.settings.enabled);hide(selectors.chat,state.settings.hideChat);hide(selectors.twitch,state.settings.hideTwitch);hide(['[class*="news"]','[class*="promo"]','[class*="leaderboard"]'],!!state.settings.focusMode);clockWarn()}
  function gameId(){const m=location.pathname.match(/\/game\/(?:live|daily)\/([^/?#]+)/i);return m?m[1]:location.href}
  function players(){const seen=new Set(),out=[];qAny(selectors.players).forEach(e=>{let n=text(e),h=e.closest('a')?.getAttribute('href')||e.getAttribute('href')||'';let m=h.match(/\/member\/([^/?#]+)/i);n=(m?.[1]||n).replace(/\s+/g,'');if(n&&!seen.has(n.toLowerCase())){seen.add(n.toLowerCase());out.push(n)}});return out}
  async function opponentPanel(){if(!state.settings.showOpponentScore)return;const opp=state.opponent||players()[0];if(!opp)return;state.opponent=opp;const d=await get(['opponents']);const rec=(d.opponents||{})[opp.toLowerCase()]||{wins:0,draws:0,losses:0};let p=root().querySelector('.zen-opponent-panel');if(!p){p=document.createElement('div');p.className='zen-opponent-panel';root().appendChild(p)}p.innerHTML=`<b>vs ${opp}</b><div>${rec.wins} W · ${rec.draws} D · ${rec.losses} L</div>`}
  function result(){const els=qAny(selectors.result).filter(visible);const s=text(els[0]||document.body).toLowerCase();if(!/you|win|lose|draw|resign|checkmate|time/.test(s))return null;if(/you (won|win)|victory/.test(s))return 'win';if(/you (lost|lose)|defeat/.test(s))return 'loss';if(/\bdraw\b|stalemate|agreement/.test(s))return 'draw';return null}
  async function record(r){if(!r||!state.opponent)return;const d=await get(['opponents']);const db=d.opponents||{};const k=state.opponent.toLowerCase();const x=db[k]||{wins:0,draws:0,losses:0,games:[]};const field={win:'wins',draw:'draws',loss:'losses'}[r];x[field]++;x.games=[...(x.games||[]),{result:r,timestamp:Date.now(),game:gameId()}].slice(-100);db[k]=x;await set({opponents:db})}
  function reviewBar(){const r=result();if(!r)return;const id=gameId();let b=root().querySelector('.zen-review');if(!b){b=document.createElement('div');b.className='zen-review';root().appendChild(b)}if(b.dataset.id===id)return;b.dataset.id=id;b.innerHTML='';const a=document.createElement('button');a.className='primary';a.textContent='Game Review';a.onclick=()=>window.open(`https://www.chess.com/analysis/game/live/${encodeURIComponent((location.pathname.match(/\/game\/[^/]+\/([^/?#]+)/i)||[])[1]||'')}`,'_blank');b.append(a)}
  function sessionUi(){if(!state.settings.showSessionPanel)return;let p=root().querySelector('.zen-session');if(p)return;p=document.createElement('div');p.className='zen-session';p.innerHTML='<h3>Session Mode</h3><div class="zen-session-grid"><label>Games<input id="zen-games" type="number" min="1" value="5"></label><label>Minutes<input id="zen-mins" type="number" min="1" value="30"></label></div><div class="zen-session-actions"><button id="zen-start">Start</button><button id="zen-stop">Stop</button></div><div class="zen-session-status" id="zen-status">No active session.</div>';root().appendChild(p);p.querySelector('#zen-start').onclick=async()=>{state.session={gamesGoal:+p.querySelector('#zen-games').value||5,minutesGoal:+p.querySelector('#zen-mins').value||30,games:0,wins:0,draws:0,losses:0,startedAt:Date.now()};await set({session:state.session});renderSession(p)};p.querySelector('#zen-stop').onclick=async()=>{state.session=null;await set({session:null});renderSession(p)};renderSession(p)}
  function renderSession(p){p.querySelector('#zen-status').textContent=state.session?`${state.session.games}/${state.session.gamesGoal} · ${state.session.wins}-${state.session.draws}-${state.session.losses}`:'No active session.'}
  function toolbar(){if(root().querySelector('.zen-toolbar'))return;const b=document.createElement('div');b.className='zen-toolbar';b.innerHTML='<button id="zen-focus">Focus</button><button id="zen-session-btn">Session</button>';root().appendChild(b);const f=b.querySelector('#zen-focus');f.onclick=async()=>{state.settings.focusMode=!state.settings.focusMode;await set({settings:state.settings});apply();f.classList.toggle('active',state.settings.focusMode)};b.querySelector('#zen-session-btn').onclick=()=>{const p=root().querySelector('.zen-session');if(p)p.style.display=p.style.display==='none'?'':'none'}}
  async function boot(){const d=await get(['settings','session']);state.settings={...DEFAULTS,...(d.settings||{})};state.session=d.session||null;toolbar();sessionUi();apply();setInterval(async()=>{apply();await opponentPanel();reviewBar();const r=result(),id=gameId();if(r&&state.lastResultKey!==id){state.lastResultKey=id;await record(r);if(state.session){state.session.games++;state.session[`${r==='win'?'wins':r==='draw'?'draws':'losses'}`]++;if(state.session.games>=state.session.gamesGoal)state.session=null;await set({session:state.session});const p=root().querySelector('.zen-session');if(p)renderSession(p)}}},800);new MutationObserver(()=>{apply();toolbar();sessionUi();opponentPanel();reviewBar()}).observe(document.body,{subtree:true,childList:true})}
  chrome.storage.onChanged.addListener(async(ch,area)=>{if(area!=='local')return;if(ch.settings){state.settings={...DEFAULTS,...(ch.settings.newValue||{})};apply()}if(ch.session){state.session=ch.session.newValue||null;const p=root().querySelector('.zen-session');if(p)renderSession(p)}});
  boot();
})();